---
title: "Intro to Git and GitHub"
output: html_notebook
---

<h2>Installing Git</h2>

Git is a free, open source version control system. It allows users to preserve a complete history of changes to a directory and changes to individual files (like R scripts!). This means that you have to try really hard to delete any of your code, so it's a good way to keep records of your data and code. You can also use Git collaboratively, so if someone else messes up your code you can go back to your version and reject all their changes. 

Go to the [Git website](https://git-scm.com/downloads) and download Git for your operating system. If you're uncomfortable working in the command line, you may want to also [download a GUI client](https://git-scm.com/downloads/guis) so that you can visualize what is happening behind the scenes with your directory and file history. However, I suggest you just get used to the command line because it's fun and you can pretend you're a hacker. 

If you're using Windows, at some point during the installation, you will need to select the options "Use Git from the Windows Command Prompt", "Checkout Windows-style, commit Unix-style line endings", and "Use Windows' default console window." Once you finish installing, open your command prompt and type <i>setx HOME "%USERPROFILE%"</i> then hit enter and you should get a success message. 

<h2>Connecting GitHub to RStudio</h2>

First, go to [GitHub](https://github.com/) and create an account. You will need to verify your email address.

Once you have created an account, go to your settings (dropdown menu is in the upper right corner) and then to SSH. Next, open RStudio and go to Tools > Gloabl Options > Git/SVN. Click on "View public key" and copy what appears in the window. Paste this into a new SSH key in GitHub. Your laptop is now authorized to make changes to your GitHub account. 

In bash, type <i>git config --global user.email "youruseremail@uconn.edu"</i> and hit enter. Then type <i>git config --global user.name "yourusername"</i>. This tells Git who you are. 

<h2>Forking a Repository</h2>
For this class, we have a master repository of course materials, notes, data, scripts, etc... You're going to want to work with these materials in RStudio, so you need to copy the entire repository to your computer. You also want to be able to suggest changes and contribute helpful scripts to the repository (especially if you're teaching a week). This means you need to fork the original repository.

To do this, go to my [GitHub account](https://github.com/elizagrames/Rstats) and fork the repository. The button to do this is in the upper right corner. When the process is done, you should be on a new page with a repository still called Rstats, but it's now associated with your profile. You've created an identical copy of my repository, but it's a snapshot in time. If I make changes to the original repository, you won't see them in your repository; similarly, I won't see changes you make. 

Next, you want to get a copy of the repository on your computer since right now it only exists on your GitHub account. To do this, go to RStudio, click on File > New Project > Version Control and enter the URL of your forked repository (https://github.com/yourusername/Rstats). The other fields should populate automatically, though you may want to change the directory you clone it into. 

Once it is cloned, you'll notice that RStudio automatically set your working directory to the cloned repository and that all the subdirectories and files are shown in your Files tab. You can now work on the project offline. 

<h2>Making Changes to the Repository</h2>

Right now, there are three copies of the same repository - my original repository, your forked repository stored on GitHub, and the repository on your computer. Changes in any one of these repositories will not affect the other two. 

In R, create a new script and save it anywhere in your Rstats repository. This is a good time to remind you that this is all going to be publicly visible as tracked changes in your repository even if you delete the files later. Once you save your script, go and look at your repository on GitHub (you might want to refresh the page). The new file isn't there. 

In order to send the changes to your online repository, you need to stage, commit, and push the changes. You have a new tab in RStudio called Git. Go to it and you'll see that your new file is listed with some question marks. This means it is untracked. Check the box to stage it, then click on Commit. You'll need to enter a Commit message (again, this is public record so you might want to just say something like "uploaded new script"). Click on the Commit button. A window will pop up and tell you it changed something. You can click close. Next, click on the green arrow labeled Push in the upper right corner. This sends your changes to your GitHub repository, which you can confirm by refreshing that page. 

<h2>Setting an Upstream Branch</h2>

Since changes in your repository don't show up in mine, I won't know if you've created a really neat script that you want to share with the group. To do this, you'll need to open a terminal and navigate to the directory (folder) where you have your repository saved locally. To navigate to the directory, type cd ~/path/to/Rstats (replacing path to with wherever you saved it, like Documents/Classes/Rstats. Type <i>git remote -v </i> to check that you have two origins, one to fetch and one to push. Next, you want to set an upstream branch (my repository) to sync with your fork. To do this, type <i>git remote add upstream https://github.com/elizagrames/Rstats.</i> Verify that the change happened by doing <i>git remote -v </i> again. 

Next, you want to fetch changes from my branch. To do this, type <i>git fetch upstream</i>, hit enter, then do <i>git checkout master</i>, hit enter, and finally do <i>git merge upstream/master</i> and hit enter. This will pull any new changes from my copy of the repository and merge them with yours. Assuming you haven't changed any of my files in a way that is unmergeable, it will go through just fine. Now, your local copy of the repository is synced with my copy, but your GitHub is behind. To send the new changes you just downloaded from me to your GitHub repository, click on the green push button. 

Now your repository should have one script that mine doesn't because even though you've pulled my changes, I'm the upstream branch and don't see what you do. To suggest that I add your script to the class repository, you need to initiate a pull request. Then I'll see the changes you've made and can either accept them into my branch or reject your changes. 

To make sure you always have the latest copy of the class materials, before you start working on them you should fetch, checkout, merge, and push. That will help prevent any double changes of the same file which can create conflicts that are annoying to resolve. 

A word of warning: NEVER <i>git push -f</i> because it will overwrite everything. You can always revert, but it's a pain. 
